/// <reference lib="dom" />
/**
 * ProcModel editor (T-311 Phase 1a) — author a procedural model (tree / plant /
 * rock) against the REAL shipped generator registry + bake path. This is the
 * "one primitive" rung of the density authoring ladder (VISUAL_DATAMODEL_PLAN
 * §Density through composition): get a single generator looking right, then it
 * composes into layers later.
 *   left   — procmodels/ asset browser.
 *   centre — the model, generated by the actual `getGenerator(def.generator)`
 *            then baked through `bakeVoxels` + `buildVoxelMaterial` (the same
 *            code path the scatter renderer runs in-game — no drift).
 *   right  — seed (+ re-roll) and a live params editor; edits re-generate instantly.
 *
 * Like the Material panel, this deliberately runs the real client render code
 * (`@voxim/client/render`).
 */
import { useEffect, useRef, useState } from "preact/hooks";
import * as THREE from "three";
import type { MaterialDef } from "@voxim/content";
import {
  bakeVoxels,
  geometryFromBaked,
  buildVoxelMaterial,
  registerBuiltinGenerators,
  getGenerator,
  generatorIds,
} from "@voxim/client/render";
import { Layout } from "../shell/Layout.tsx";
import { AssetBrowser } from "../shell/AssetBrowser.tsx";
import { ViewportPane } from "../shell/ViewportPane.tsx";
import { listDir, readJson, writeJson } from "../shell/file_io.ts";
import type { Viewport } from "../shell/viewport.ts";

interface MaterialJson extends Omit<MaterialDef, "color"> { color: string | number; }
interface ProcModelJson { id: string; generator: string; params: Record<string, unknown>; }

function parseColor(c: string | number): number {
  return typeof c === "string" ? parseInt(c.replace(/^#/, ""), 16) : c;
}
function safeParse(s: string): Record<string, unknown> | null {
  try { return JSON.parse(s) as Record<string, unknown>; } catch { return null; }
}

export function ProcModelEditor() {
  registerBuiltinGenerators(); // idempotent — the same registry the client boots

  const [byName, setByName]   = useState<Map<string, MaterialJson>>(new Map());
  const [pm, setPm]           = useState<ProcModelJson | null>(null);
  const [paramsText, setText] = useState("{}");
  const [seed, setSeed]       = useState(12345);
  const [atoms, setAtoms]     = useState(0);
  const [err, setErr]         = useState<string | null>(null);
  const [path, setPath]       = useState<string | null>(null);
  const [dirty, setDirty]     = useState(false);
  const viewportRef = useRef<Viewport | null>(null);
  const groupRef    = useRef<THREE.Group | null>(null);

  // Load every material once (name→def for the generator ctx + colour/render).
  useEffect(() => {
    (async () => {
      const entries = await listDir("materials");
      const map = new Map<string, MaterialJson>();
      for (const e of entries) {
        if (e.kind !== "file" || !e.name.endsWith(".json")) continue;
        try {
          const m = await readJson<MaterialJson>(`materials/${e.name}`);
          map.set(m.name, m);
        } catch { /* skip */ }
      }
      setByName(map);
    })();
  }, []);

  const rebuild = (
    def: ProcModelJson,
    params: Record<string, unknown>,
    sd: number,
    mats: Map<string, MaterialJson>,
  ) => {
    const vp = viewportRef.current;
    if (!vp || mats.size === 0) return;
    if (groupRef.current) {
      vp.contentGroup.remove(groupRef.current);
      groupRef.current.traverse((o) => {
        const m = o as THREE.Mesh;
        m.geometry?.dispose?.();
        (m.material as THREE.Material | undefined)?.dispose?.();
      });
    }
    try {
      const gen = getGenerator(def.generator);
      if (!gen) throw new Error(`unknown generator "${def.generator}" (have: ${generatorIds().join(", ")})`);
      const byId = new Map<number, MaterialJson>();
      for (const m of mats.values()) byId.set(m.id, m);
      const ctx = {
        resolveMaterial: (name: string): number => {
          const m = mats.get(name);
          if (!m) throw new Error(`generator references unknown material "${name}"`);
          return m.id;
        },
      };
      const built = gen(sd, params, ctx);
      const group = new THREE.Group();
      for (const id of new Set(built.map((a) => a.materialId))) {
        const mj = byId.get(id);
        const matDef = mj ? ({ ...mj, color: parseColor(mj.color) } as unknown as MaterialDef) : undefined;
        const baked = bakeVoxels(built, id, undefined, matDef?.render?.tintJitter);
        group.add(new THREE.Mesh(geometryFromBaked(baked), buildVoxelMaterial(matDef, id)));
      }
      vp.contentGroup.add(group);
      groupRef.current = group;
      vp.frame(new THREE.Box3().setFromObject(group));
      setAtoms(built.length);
      setErr(null);
    } catch (e) {
      setErr(e instanceof Error ? e.message : String(e));
      setAtoms(0);
    }
  };

  // Re-generate once materials arrive (a pick may land before they load).
  useEffect(() => {
    if (pm && byName.size > 0) rebuild(pm, safeParse(paramsText) ?? pm.params, seed, byName);
  }, [byName]);

  const pick = async (p: string) => {
    if (!p.endsWith(".json")) return;
    const def = await readJson<ProcModelJson>(p);
    setPm(def);
    setPath(p);
    setDirty(false);
    setText(JSON.stringify(def.params ?? {}, null, 2));
    rebuild(def, def.params ?? {}, seed, byName);
  };

  const save = async () => {
    if (!pm || !path) return;
    const params = safeParse(paramsText);
    if (!params) return; // never persist invalid JSON
    await writeJson(path, { ...pm, params });
    setDirty(false);
  };

  const reroll = () => {
    const sd = Math.floor(Math.random() * 1e9);
    setSeed(sd);
    if (pm) rebuild(pm, safeParse(paramsText) ?? pm.params, sd, byName);
  };

  const onParams = (text: string) => {
    setText(text);
    const p = safeParse(text);
    if (p && pm) { setDirty(true); rebuild(pm, p, seed, byName); }
  };

  return (
    <Layout
      topBar={
        <>
          <span class="dt-brand" style={{ marginRight: "auto" }}>ProcModel</span>
          {pm && <span style={{ color: "var(--bone-faint)", marginRight: 12 }}>{pm.id} · {pm.generator} · {atoms} atoms</span>}
          {pm && <button class="dt-btn" disabled={!dirty} onClick={save}>{dirty ? "Save *" : "Saved"}</button>}
        </>
      }
      left={<AssetBrowser filter={["procmodels"]} onPickFile={pick} />}
      centre={
        <ViewportPane
          onReady={(vp) => {
            viewportRef.current = vp;
            if (pm) rebuild(pm, safeParse(paramsText) ?? pm.params, seed, byName);
          }}
        />
      }
      right={
        <div style={{ padding: "var(--s-4)", display: "flex", flexDirection: "column", gap: "var(--s-4)" }}>
          {!pm && <div style={{ color: "var(--bone-faint)" }}>Pick a procmodel on the left.</div>}
          {pm && (
            <>
              <div>
                <div style={{ color: "var(--bone)", fontSize: "var(--fs-small)", marginBottom: 6, textTransform: "uppercase", letterSpacing: "0.04em" }}>Seed</div>
                <div style={{ display: "flex", gap: 8, alignItems: "center" }}>
                  <input
                    class="dt-input" type="number" value={seed} style={{ flex: 1 }}
                    onInput={(e) => {
                      const sd = parseInt((e.target as HTMLInputElement).value, 10) || 0;
                      setSeed(sd);
                      if (pm) rebuild(pm, safeParse(paramsText) ?? pm.params, sd, byName);
                    }}
                  />
                  <button class="dt-btn" onClick={reroll}>re-roll</button>
                </div>
              </div>
              <div>
                <div style={{ color: "var(--bone)", fontSize: "var(--fs-small)", marginBottom: 6, textTransform: "uppercase", letterSpacing: "0.04em" }}>Params</div>
                <textarea
                  class="dt-input"
                  value={paramsText}
                  spellcheck={false}
                  style={{ width: "100%", height: 220, fontFamily: "var(--font-mono)", fontSize: "var(--fs-small)", resize: "vertical" }}
                  onInput={(e) => onParams((e.target as HTMLTextAreaElement).value)}
                />
                {!safeParse(paramsText) && <div style={{ color: "var(--blood)", fontSize: "var(--fs-small)" }}>invalid JSON — not applied</div>}
              </div>
              {err && (
                <div style={{ color: "var(--blood)", fontSize: "var(--fs-small)", lineHeight: 1.5 }}>
                  generator error: {err}
                </div>
              )}
              <div style={{ color: "var(--bone-faint)", fontSize: "var(--fs-small)", lineHeight: 1.5 }}>
                Generated by the real <code>{pm.generator}</code> + baked through the shipped
                <code> bakeVoxels</code> — identical to in-game scatter. The full density slice
                (multi-layer scatter painting) lands with the Phase-3 field grids.
              </div>
            </>
          )}
        </div>
      }
    />
  );
}
