/**
 * Generate `models/biped_skeletal.json` from `skeletons/biped.json`.
 *
 * For each bone in the biped, emit one sub-object that attaches a generic
 * `bone_segment` voxel model and scales it to the right length and a thin
 * radius. Mixamo bones have their local +Y aligned with the bone direction
 * (toward the child), so the column fills the bone with no extra rotation.
 *
 * Length is derived from the bone's primary child's offset magnitude.
 * Terminal bones (head, hand, foot) use a small fixed length so they're
 * visible as nubs.
 *
 * Run:
 *   deno run -A scripts/build_skeletal.ts > packages/content/data/models/biped_skeletal.json
 */

interface BoneDef {
  id: string;
  parent: string | null;
  restX: number;
  restY: number;
  restZ: number;
  restRotX?: number;
  restRotY?: number;
  restRotZ?: number;
}

interface SkeletonDef {
  id: string;
  bones: BoneDef[];
}

const biped = JSON.parse(
  await Deno.readTextFile("packages/content/data/skeletons/biped.json"),
) as SkeletonDef;

// Primary anatomical children — used to compute each bone's segment length.
// For multi-child bones (torso_lower has both torso_mid and the legs;
// torso_upper has both head and the arms) we pick the bone in the same
// chain so the segment runs along the visible spine direction.
const PRIMARY_CHILD: Record<string, string> = {
  root:        "torso_lower",
  torso_lower: "torso_mid",
  torso_mid:   "torso_upper",
  torso_upper: "head",
  upper_arm_l: "lower_arm_l",
  lower_arm_l: "hand_l",
  upper_arm_r: "lower_arm_r",
  lower_arm_r: "hand_r",
  upper_leg_l: "lower_leg_l",
  lower_leg_l: "foot_l",
  upper_leg_r: "lower_leg_r",
  lower_leg_r: "foot_r",
};

// Terminal bones get a fixed visible nub length so they're not invisible.
const TERMINAL_LENGTH: Record<string, number> = {
  head:   0.55,
  hand_l: 0.30,
  hand_r: 0.30,
  foot_l: 0.45,
  foot_r: 0.45,
};

// Per-bone radius (in entity-local units, before entity scale). Thicker for
// the spine / pelvis, thinner for limbs. The bone_segment model is 1 voxel
// wide so transform.scaleX/Z is the radius.
const RADIUS: Record<string, number> = {
  root:        0.20,
  torso_lower: 0.32,
  torso_mid:   0.30,
  torso_upper: 0.34,
  head:        0.36,
  upper_arm_l: 0.18, lower_arm_l: 0.16, hand_l: 0.18,
  upper_arm_r: 0.18, lower_arm_r: 0.16, hand_r: 0.18,
  upper_leg_l: 0.24, lower_leg_l: 0.22, foot_l: 0.22,
  upper_leg_r: 0.24, lower_leg_r: 0.22, foot_r: 0.22,
};

// Resolve each bone's offset magnitude (= child's translation length).
const boneById = new Map<string, BoneDef>(biped.bones.map((b) => [b.id, b]));
function offsetMagnitude(bone: BoneDef): number {
  return Math.sqrt(bone.restX ** 2 + bone.restY ** 2 + bone.restZ ** 2);
}

interface SubObject {
  modelId: string;
  boneId: string;
  transform: {
    x: number; y: number; z: number;
    rotX: number; rotY: number; rotZ: number;
    scaleX: number; scaleY: number; scaleZ: number;
  };
  hitbox?: false;
}

const SEGMENT_VOXEL_LENGTH = 4; // bone_segment.json has 4 voxels along Y

const subObjects: SubObject[] = [];
for (const bone of biped.bones) {
  // Skip the synthetic root for now — it's at (0,0,0) and overlaps with
  // torso_lower's segment. Could draw a small marker if useful later.
  if (bone.id === "root") continue;

  let length: number;
  const childId = PRIMARY_CHILD[bone.id];
  if (childId) {
    const child = boneById.get(childId);
    if (!child) {
      console.error(`[build_skeletal] missing child ${childId} for ${bone.id}`);
      continue;
    }
    length = offsetMagnitude(child);
  } else if (TERMINAL_LENGTH[bone.id] !== undefined) {
    length = TERMINAL_LENGTH[bone.id];
  } else {
    console.error(`[build_skeletal] no length rule for bone ${bone.id} — skipping`);
    continue;
  }

  const radius = RADIUS[bone.id] ?? 0.20;

  subObjects.push({
    modelId: "bone_segment",
    boneId: bone.id,
    transform: {
      // bone_segment.json's voxels are stacked along its model +Z axis
      // (entity-local up). The entity-to-three.js axis swap maps that to
      // three.js +Y, which is also where the bone's bind rotation puts its
      // local +Y in world space (Mixamo convention: bone-local +Y = bone
      // direction). So scaleZ stretches the column along the bone, while
      // scaleX/Y set the perpendicular thickness.
      x: 0, y: 0, z: 0,
      rotX: 0, rotY: 0, rotZ: 0,
      scaleX: radius * 2,
      scaleY: radius * 2,
      scaleZ: length / SEGMENT_VOXEL_LENGTH,
    },
    hitbox: false, // skeletal viz is purely visual; HitboxSystem derives capsules from the skeleton
  });
}

const out = {
  _comment:
    "Auto-generated by scripts/build_skeletal.ts from skeletons/biped.json. Each bone gets a thin cylinder (bone_segment) attached and scaled to its segment length. Lengths come from each bone's primary child's offset magnitude; terminals (head, hand, foot) use a small fixed nub.",
  id: "biped_skeletal",
  version: 1,
  skeletonId: "biped",
  nodes: [],
  subObjects,
  materials: [105],
};

console.log(JSON.stringify(out, null, 2));
